### ISSUE TITLE
Add to maven central 

### ISSUE THREAD

**Issue by kdabir** [medly/ktee#2]
Since most builds already have dependency repos configured for mavenCentral or jcenter, it would be good to add it to more common repo. We will keep this issue open. If it gets enough votes (10+)  then it would be worth the effort of adding to maven central. Otherwise jitpack should work just fine.

**Comment by niraj8** [comment]
We now have a workflow set up to publish to Maven Central on Github Release

https://repo.maven.apache.org/maven2/com/medly/ktee/1.0.0/
